Vagrant::Config.run do |config|
  config.vm.box     = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

  # forward from guest to host
  config.vm.forward_port 3306, 3306

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "base.pp"
    puppet.module_path    = "modules"
    puppet.options = "--verbose"
  end
end
